In [ ]:
"Open in Google Colab:" [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/LazyBonesGIS/lab4/exercises.ipynb)

import random

#exercise 1
latitude_nyc = 40.7128
longitude_nyc = -74.0060
population_nyc = 8336817
area_nyc = 783.8

# population density
population_density = population_nyc / area_nyc
print(f"population density: {population_density:.2f} people/kmsq")
print(f"latitude: {latitude_nyc}, longitude: {longitude_nyc}")

#exercise 2
city_name = "San Francisco"
print(city_name.lower())
print(city_name.upper())
print(city_name.replace("San","Los"))

#exercise 3
cities = [("New York City", (40.7128, -74.0060)),
          ("Los Angeles", (34.0522, -118.2437)),
          ("Chicago", (41.8781, -87.6298))]
cities.append(("Miami", (25.7617, -80.1918)))
print(cities)
print(cities[:2])

#exercise 4
eiffel_tower_coords = (48.8584, 2.2945)
print(f"latitude: {eiffel_tower_coords[0]}, Longitude: {eiffel_tower_coords[1]}")
# eiffel_tower_coords[1] = 48.8585
#'tuple object does not support item assignment'

#exercise 5
visited_countries = {"USA", "Mexico"}
visited_countries.add("Canada")
visited_countries.add("Canada")
print(visited_countries)
# The duplicates are printed as one.

#exercise 6
river = {"Name": "Amazon River", "Length": 6400, "Countries": ["Brazil", "Peru", "Colombia"]}
river["Average Discharge"] = 209000
river["Length"] = 6992
print(river)

#exercise 7
tokyo = {"Name": "Tokyo", "Population": 13515271, "Coordinates": (35.6895, 139.6917)}
print(tokyo["Population"])
print(tokyo["Coordinates"][0])
tokyo["Population"] = 14000000
print(tokyo)

#exercise 8
cities.sort()
city_names = [city[0] for city in cities]
cities.pop()
print(cities)

#exercise 9
print("Length" in river)
print(river.keys())
print(river.values())

#exercise 10
locations = [("Mount Everest", 27.9881, 86.9250),
             ("K2", 35.8808, 76.5155),
             ("Kangchenjunga", 27.7025, 88.1475)]
location_names = [loc[0] for loc in locations]
location_dict = {loc[0]: (loc[1], loc[2]) for loc in locations}
print(location_dict["K2"][0])

#exercise 11
feature = "Amazon River"
print(feature.lower())
print(feature.upper())
print(feature + " - Brazil")
print((feature + "-") * 2 + feature)

#exercise 12
coord_string = "40.7128N, 74.0060W"
lat, lon = coord_string.replace("N", "").replace("W", "").split(", ")
lat, lon = float(lat), -float(lon)
print(f"POINT({lon} {lat})")

#exercise 13
def sql_query(table_name, condition):
    return f"SELECT * FROM {table_name} WHERE {condition};"
print(sql_query("cities", "population > 1000000"))

#exercise 14
raw_cities = [" new york ", "Los ANGELES", "   CHICAGO"]
clean_cities = [city.strip().title() for city in raw_cities]
print(clean_cities)

#exercise 15
def parse_address(address):
    street, city, country = address.split(", ")
    return {"street": street, "city": city, "country": country}
print(parse_address("123 Main St, Springfield, USA"))

#exercise 16
coordinates = [(40.7128, -74.0060), (-33.8688, 151.2093), (51.5074, -0.1278)]
for lat, lon in coordinates:
    hemisphere = "Northern" if lat >= 0 else "Southern"
    print(f"Coordinate: ({lat}, {lon}) is in the {hemisphere} Hemisphere")

#exercise 17
index = 0
while index < len(coordinates):
    lat, lon = coordinates[index]
    if lat < 0:
        break
    print(f"Processing coordinate: {lat}, {lon}")
    index += 1

#exercise 18
for lat, lon in coordinates:
    if lon > 0:
        print("Eastern Hemisphere")
    elif lon < 0:
        print("Western Hemisphere")
    else:
        print("Prime Meridian")

#exercise 19
southern_hemisphere = [coord for coord in coordinates if coord[0] < 0]
print(f"Southern Hemisphere coordinates: {southern_hemisphere}")

#exercise 20
while True:
    lat = random.uniform(-90, 90)
    lon = random.uniform(-180, 180)
    print(f"Generated: ({lat:.4f}, {lon:.4f})")
    if lat > 50 and lon > 50:
        print(f"Final coordinate meeting condition: ({lat}, {lon})")
        break

population density: 10636.41 people/kmsq
latitude: 40.7128, longitude: -74.006
san francisco
SAN FRANCISCO
Los Francisco
[('New York City', (40.7128, -74.006)), ('Los Angeles', (34.0522, -118.2437)), ('Chicago', (41.8781, -87.6298)), ('Miami', (25.7617, -80.1918))]
[('New York City', (40.7128, -74.006)), ('Los Angeles', (34.0522, -118.2437))]
latitude: 48.8584, Longitude: 2.2945
{'Mexico', 'USA', 'Canada'}
{'Name': 'Amazon River', 'Length': 6992, 'Countries': ['Brazil', 'Peru', 'Colombia'], 'Average Discharge': 209000}
13515271
35.6895
{'Name': 'Tokyo', 'Population': 14000000, 'Coordinates': (35.6895, 139.6917)}
[('Chicago', (41.8781, -87.6298)), ('Los Angeles', (34.0522, -118.2437)), ('Miami', (25.7617, -80.1918))]
True
dict_keys(['Name', 'Length', 'Countries', 'Average Discharge'])
dict_values(['Amazon River', 6992, ['Brazil', 'Peru', 'Colombia'], 209000])
35.8808
amazon river
AMAZON RIVER
Amazon River - Brazil
Amazon River-Amazon River-Amazon River
POINT(-74.006 40.7128)
SELECT * FROM cities WHERE population > 1000000;
['New York', 'Los Angeles', 'Chicago']
{'street': '123 Main St', 'city': 'Springfield', 'country': 'USA'}
Coordinate: (40.7128, -74.006) is in the Northern Hemisphere
Coordinate: (-33.8688, 151.2093) is in the Southern Hemisphere
Coordinate: (51.5074, -0.1278) is in the Northern Hemisphere
Processing coordinate: 40.7128, -74.006
Western Hemisphere
Eastern Hemisphere
Western Hemisphere
Southern Hemisphere coordinates: [(-33.8688, 151.2093)]
Generated: (-59.5542, -102.8675)
Generated: (75.7662, -175.4352)
Generated: (72.4900, 150.1791)
Final coordinate meeting condition: (72.48995975876906, 150.17914575362101)